all :	
	yacc -d lab4docalc.y #compiles YACC file 
	lex lab4docalc.l  #compiles lex file
	gcc y.tab.c lex.yy.c symtable.c -o lab4docalc #compiles lex.yy.c and symbol table file and creates executable 
